server:
    port: 8090

spring:
    datasource:
        url: jdbc:postgresql://bookstore-db:5432/bookstore
        username: root
        password: qwer1234

mybatis:
    type-aliases-package: com.example.bookstorepayment.entity